# Generated by Django 6.0.4 on 2026-10-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Dátum a čas vytvorenia záznamu",
                        verbose_name="Vytvorené",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Dátum a čas poslednej úpravy",
                        verbose_name="Aktualizované",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný, ak nie je vyplnený)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Určuje, či je záznam verejne viditeľný",
                        verbose_name="Publikované",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dátum a čas publikovania",
                        null=True,
                        verbose_name="Publikované dňa",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Názov uzla, napr. Adam Smith alebo Klasická ekonómia",
                        max_length=200,
                        verbose_name="Názov",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("person", "Osobnosť"),
                            ("school", "Ekonomická škola"),
                            ("theory", "Teória / smer"),
                            ("work", "Dielo"),
                            ("event", "Udalosť"),
                        ],
                        db_index=True,
                        help_text="Typ prvku v rodokmeni ekonómie",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "year_from",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Začiatočný rok alebo rok vzniku",
                        null=True,
                        verbose_name="Rok od",
                    ),
                ),
                (
                    "year_to",
                    models.IntegerField(
                        blank=True,
                        help_text="Koncový rok, ak je relevantný",
                        null=True,
                        verbose_name="Rok do",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Stručný popis vhodný pre graf a časovú os",
                        verbose_name="Krátky popis",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Podrobnejšie informácie zobrazované v detaile uzla",
                        verbose_name="Detailný popis",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Manuálne poradie pri zobrazovaní uzlov",
                        verbose_name="Poradie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uzol",
                "verbose_name_plural": "Uzly",
                "ordering": ["order", "year_from", "name"],
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Dátum a čas vytvorenia záznamu",
                        verbose_name="Vytvorené",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Dátum a čas poslednej úpravy",
                        verbose_name="Aktualizované",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Určuje, či je záznam verejne viditeľný",
                        verbose_name="Publikované",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dátum a čas publikovania",
                        null=True,
                        verbose_name="Publikované dňa",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("influenced", "Ovplyvnil"),
                            ("represents", "Predstaviteľ"),
                            ("founded", "Zakladateľ"),
                            ("developed", "Rozvinul"),
                            ("author", "Autor"),
                            ("reacted_to", "Reakcia na"),
                            ("opposed", "Vymedzil sa voči"),
                            ("related", "Súvisí s"),
                        ],
                        db_index=True,
                        help_text="Význam vzťahu medzi uzlami",
                        max_length=20,
                        verbose_name="Typ prepojenia",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Voliteľné vysvetlenie vzťahu medzi uzlami",
                        verbose_name="Popis",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manuálne poradie prepojenia",
                        verbose_name="Poradie",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Uzol, z ktorého vzťah vychádza",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="rodokmen.node",
                        verbose_name="Zdroj",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Uzol, do ktorého vzťah smeruje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="rodokmen.node",
                        verbose_name="Cieľ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prepojenie",
                "verbose_name_plural": "Prepojenia",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target", "connection_type"),
                        name="unique_rodokmen_connection",
                    )
                ],
            },
        ),
    ]
