# Generated by Django 6.0.4 on 2026-10-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rodokmen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="period_label",
            field=models.CharField(
                blank=True,
                help_text="Voliteľný text zobrazovaný namiesto rokov, napr. '18. storočie', 'druhá polovica 19. storočia' alebo 'stredovek'.",
                max_length=100,
                verbose_name="Označenie obdobia",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="year_from",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Začiatočný rok, rok narodenia alebo približný začiatok obdobia. Používa sa aj na chronologické zoradenie.",
                null=True,
                verbose_name="Rok od",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="year_to",
            field=models.IntegerField(
                blank=True,
                help_text="Koncový rok, rok úmrtia alebo približný koniec obdobia, ak je relevantný.",
                null=True,
                verbose_name="Rok do",
            ),
        ),
    ]
