# Generated by Django 6.0.4 on 2026-10-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rodokmen", "0002_node_period_label_alter_node_year_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("influenced", "Ovplyvnil"),
                    ("represents", "Predstaviteľ"),
                    ("founded", "Zakladateľ"),
                    ("developed", "Rozvinul"),
                    ("author", "Autor"),
                    ("reacted_to", "Reakcia na"),
                    ("opposed", "Vymedzil sa voči"),
                    ("related", "Súvisí s"),
                    ("belongs_to", "Patrí do"),
                    ("followed", "Nadviazal na"),
                ],
                db_index=True,
                help_text="Význam vzťahu medzi uzlami",
                max_length=20,
                verbose_name="Typ prepojenia",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("person", "Osobnosť"),
                    ("school", "Ekonomická škola"),
                    ("theory", "Teória / smer"),
                    ("concept", "Pojem / koncept"),
                    ("work", "Dielo"),
                    ("event", "Udalosť"),
                ],
                db_index=True,
                help_text="Typ prvku v rodokmeni ekonómie",
                max_length=20,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="period_label",
            field=models.CharField(
                blank=True,
                help_text="Voliteľné slovné obdobie, napr. 18. storočie, koniec 19. storočia alebo od 1930",
                max_length=100,
                verbose_name="Obdobie",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="year_from",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Začiatočný rok alebo rok vzniku",
                null=True,
                verbose_name="Rok od",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="year_to",
            field=models.IntegerField(
                blank=True,
                help_text="Koncový rok, ak je relevantný",
                null=True,
                verbose_name="Rok do",
            ),
        ),
    ]
