# Generated by Django 6.0.4 on 2026-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rodokmen", "0003_alter_connection_connection_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="editor_note",
            field=models.TextField(blank=True, verbose_name="Poznámka redaktora"),
        ),
    ]
