# Generated by Django 6.0.4 on 2026-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rodokmen", "0004_node_editor_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("influenced", "Ovplyvnil"),
                    ("represents", "Predstaviteľ"),
                    ("founded", "Zakladateľ"),
                    ("developed", "Rozvinul"),
                    ("author", "Autor"),
                    ("reacted_to", "Reakcia na"),
                    ("opposed", "Vymedzil sa voči"),
                    ("criticized", "Kritizoval"),
                    ("related", "Súvisí s"),
                    ("belongs_to", "Patrí do"),
                    ("followed", "Nadviazal na"),
                ],
                db_index=True,
                help_text="Význam vzťahu medzi uzlami",
                max_length=20,
                verbose_name="Typ prepojenia",
            ),
        ),
    ]
