# Generated by Django 6.0.4 on 2026-10-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rodokmen", "0005_alter_connection_connection_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("person", "Osobnosť"),
                    ("school", "Ekonomická škola"),
                    ("theory", "Teória / smer"),
                    ("concept", "Pojem / koncept"),
                    ("method", "Metóda / prístup"),
                    ("work", "Dielo"),
                    ("event", "Udalosť"),
                ],
                db_index=True,
                help_text="Typ prvku v rodokmeni ekonómie",
                max_length=20,
                verbose_name="Typ",
            ),
        ),
    ]
