# Generated by Django 6.0.4 on 2026-04-12 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Názov položky')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Množstvo')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za jednotku')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Suma')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Číslo faktúry')),
                ('issue_date', models.DateField(verbose_name='Dátum vystavenia')),
                ('due_date', models.DateField(verbose_name='Dátum splatnosti')),
                ('delivery_date', models.DateField(verbose_name='Dátum dodania')),
                ('variable_symbol', models.CharField(blank=True, max_length=20, verbose_name='Variabilný symbol')),
                ('constant_symbol', models.CharField(default='0308', max_length=4, verbose_name='Konštantný symbol')),
                ('specific_symbol', models.CharField(blank=True, max_length=20, verbose_name='Špecifický symbol')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Celková suma')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Zmazaná')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices', to='entities.entity', verbose_name='Odberateľ')),
            ],
        ),
    ]
