# Generated by Django 5.2.10 on 2026-01-26 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0002_entity_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Číslo faktúry"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Dátum vystavenia")),
                ("due_date", models.DateField(verbose_name="Dátum splatnosti")),
                ("delivery_date", models.DateField(verbose_name="Dátum dodania")),
                (
                    "variable_symbol",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Variabilný symbol"
                    ),
                ),
                (
                    "constant_symbol",
                    models.CharField(
                        default="0308", max_length=4, verbose_name="Konštantný symbol"
                    ),
                ),
                (
                    "specific_symbol",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Špecifický symbol"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Celková suma",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Zmazaná"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvorené"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizované"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_invoices",
                        to="entities.entity",
                        verbose_name="Odberateľ",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vlastník",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_invoices",
                        to="entities.entity",
                        verbose_name="Dodávateľ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Názov položky"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Množstvo"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena za jednotku"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="Suma",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                        verbose_name="Faktúra",
                    ),
                ),
            ],
        ),
    ]
