# Generated by Django 5.2.10 on 2026-01-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Číslo faktúry"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Dátum vystavenia")),
                ("due_date", models.DateField(verbose_name="Dátum splatnosti")),
                ("delivery_date", models.DateField(verbose_name="Dátum dodania")),
                (
                    "supplier_iban",
                    models.CharField(max_length=34, verbose_name="IBAN dodávateľa"),
                ),
                (
                    "customer_iban",
                    models.CharField(
                        blank=True, max_length=34, verbose_name="IBAN odberateľa"
                    ),
                ),
                (
                    "variable_symbol",
                    models.CharField(max_length=20, verbose_name="Variabilný symbol"),
                ),
                (
                    "constant_symbol",
                    models.CharField(
                        default="0308", max_length=4, verbose_name="Konštantný symbol"
                    ),
                ),
                (
                    "specific_symbol",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Špecifický symbol"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=255, verbose_name="Názov dodávateľa"),
                ),
                (
                    "supplier_ico",
                    models.CharField(max_length=20, verbose_name="IČO dodávateľa"),
                ),
                (
                    "supplier_dic",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="DIČ dodávateľa"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        max_length=255, verbose_name="Obchodné meno / meno a priezvisko"
                    ),
                ),
                (
                    "customer_ico",
                    models.CharField(blank=True, max_length=20, verbose_name="IČO"),
                ),
                (
                    "customer_dic",
                    models.CharField(blank=True, max_length=20, verbose_name="DIČ"),
                ),
                (
                    "customer_ic_dph",
                    models.CharField(blank=True, max_length=20, verbose_name="IČ DPH"),
                ),
                (
                    "customer_street",
                    models.CharField(max_length=255, verbose_name="Ulica"),
                ),
                (
                    "customer_street_number",
                    models.CharField(max_length=50, verbose_name="Číslo"),
                ),
                (
                    "customer_city",
                    models.CharField(max_length=100, verbose_name="Mesto"),
                ),
                ("customer_zip", models.CharField(max_length=10, verbose_name="PSČ")),
                (
                    "customer_country",
                    models.CharField(max_length=100, verbose_name="Krajina"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email odberateľa"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Celková suma",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Zmazaná"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvorené"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizované"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Názov položky"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Množstvo"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena za jednotku"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="Suma",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                        verbose_name="Faktúra",
                    ),
                ),
            ],
        ),
    ]
