# Generated by Django 6.0.4 on 2026-05-02 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_alter_bankaccount_options_alter_entity_options"),
        ("invoices", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-issue_date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="invoice",
            name="delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="Dátum dodania"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=20, verbose_name="Číslo faktúry"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["owner", "number"], name="invoices_in_owner_i_ba99e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("owner", "number"), name="unique_invoice_per_owner"
            ),
        ),
    ]
