# Generated by Django 6.0.4 on 2026-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Dátum a čas vytvorenia záznamu",
                        verbose_name="Vytvorené",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Dátum a čas poslednej úpravy",
                        verbose_name="Aktualizované",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný, ak nie je vyplnený)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Určuje, či je záznam verejne viditeľný",
                        verbose_name="Publikované",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dátum a čas publikovania",
                        null=True,
                        verbose_name="Publikované dňa",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "Článok",
                "verbose_name_plural": "Články",
                "ordering": ["-created_at"],
            },
        ),
    ]
