# Generated by Django 6.0.4 on 2026-05-03 13:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
