# Generated by Django 5.2.10 on 2026-01-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Názov subjektu"),
                ),
                (
                    "ico",
                    models.CharField(blank=True, max_length=20, verbose_name="IČO"),
                ),
                (
                    "dic",
                    models.CharField(blank=True, max_length=20, verbose_name="DIČ"),
                ),
                (
                    "ic_dph",
                    models.CharField(blank=True, max_length=20, verbose_name="IČ DPH"),
                ),
                (
                    "street",
                    models.CharField(max_length=255, verbose_name="Ulica a číslo"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Mesto")),
                ("zip_code", models.CharField(max_length=10, verbose_name="PSČ")),
                (
                    "country",
                    models.CharField(
                        default="Slovensko", max_length=100, verbose_name="Krajina"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subjekt",
                "verbose_name_plural": "Subjekty",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(max_length=34, verbose_name="IBAN")),
                (
                    "swift",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="SWIFT / BIC"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Predvolený účet"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="entities.entity",
                        verbose_name="Subjekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bankový účet",
                "verbose_name_plural": "Bankové účty",
            },
        ),
    ]
