# Generated by Django 5.2.10 on 2026-01-25 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_entity_owner(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")
    Entity = apps.get_model("entities", "Entity")

    default_owner = User.objects.order_by("id").first()
    if not default_owner:
        return

    Entity.objects.filter(owner__isnull=True).update(owner=default_owner)


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="owner",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_entity_owner),
        migrations.AlterField(
            model_name="entity",
            name="owner",
            field=models.ForeignKey(
                null=False,
                blank=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
