# Generated by Django 6.0.4 on 2026-05-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "ordering": ["-is_default"],
                "verbose_name": "Bankový účet",
                "verbose_name_plural": "Bankové účty",
            },
        ),
        migrations.AlterModelOptions(
            name="entity",
            options={
                "ordering": ["name"],
                "verbose_name": "Subjekt",
                "verbose_name_plural": "Subjekty",
            },
        ),
    ]
